apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: neten-deploy
  name: neten-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neten-deploy
  template:
    metadata:
      labels:
        app: neten-deploy
    spec:
      containers:
      - image: nend895/takin:13
        name: pet
